<?php

declare(strict_types=1);

namespace Engelsystem\Controllers\Admin;

use Engelsystem\Application;
use Engelsystem\Config\Config;
use Engelsystem\Helpers\Authenticator;
use Engelsystem\Helpers\Carbon;
use Engelsystem\Helpers\CarbonDay;
use Engelsystem\Http\Exceptions\HttpForbidden;
use Engelsystem\Http\Exceptions\HttpNotFound;
use Engelsystem\Http\Redirector;
use Engelsystem\Http\Request;
use Engelsystem\Http\Response;
use Engelsystem\Models\EventConfig;
use Illuminate\Support\Str;
use InvalidArgumentException;
use Psr\Log\LoggerInterface;

class ConfigController extends BaseConfigController
{
    protected string $localConfig;

    protected string $passwordPlaceholder = '**********';

    public function __construct(
        Application $app,
        protected Config $config,
        protected Authenticator $auth,
        protected Redirector $redirect,
        protected Response $response,
        protected LoggerInterface $log,
    ) {
        parent::__construct();
        $this->localConfig = $app->get('path.config') . '/config.local.php';
        $localConfigWriteable = $this->isFileWritable($this->localConfig);
        $this->parseOptions($localConfigWriteable);
    }

    public function index(): Response
    {
        return $this->redirect->to('/admin/config/' . array_key_first($this->options));
    }

    public function edit(Request $request): Response
    {
        $page = $this->activePage($request);

        if (empty($this->options[$page]['url_added'])) {
            return $this->redirect->to($this->options[$page]['url']);
        }

        return $this->response->withView(
            'admin/config/index',
            [
                ...$this->getPageData($page),
            ]
        );
    }

    public function save(Request $request): Response
    {
        $page = $this->activePage($request);
        $data = $this->validation($page, $request);
        $settings = $this->filterShownSettings($this->options[$page]['config']);
        $localConfigWritable = $this->isFileWritable($this->localConfig);

        $changes = [];
        foreach ($settings as $key => $options) {
            # Request field names with . are parsed with _
            $fieldKey = Str::replace('.', '_', $key);
            $default = $options['default'] ?? null;
            $value = array_key_exists($fieldKey, $data) ? $data[$fieldKey] : $default;

            $value = match ($options['type']) {
                'datetime-local' => $value ? Carbon::createFromDatetime($value) : $value,
                'date' => $value ? CarbonDay::createFromDay($value) : $value,
                'boolean' => !empty($value),
                'number' => (float) $value,
                'password' => $value === $this->passwordPlaceholder ? $this->config->get($key) : $value,
                'select_multi' => is_null($value) ? [] : $value,
                default => $value,
            };

            if ($this->config->get($key) == $value) {
                continue;
            }

            $writeBack = $options['write_back'] ?? false;
            $setValue = $value !== $default && !is_null($value) && $value !== '';
            if ($setValue && !$writeBack) {
                (new EventConfig())
                    ->findOrNew($key)
                    ->setAttribute('name', $key)
                    ->setAttribute('value', $value)
                    ->save();
            } else {
                (new EventConfig())
                    ->whereName($key)
                    ->delete();
            }

            $this->config->set($key, $value);

            if ($writeBack && $localConfigWritable) {
                $oldConfig = [];
                if (file_exists($this->localConfig)) {
                    $oldConfig = include $this->localConfig;
                }
                $config = new Config($oldConfig);
                if ($setValue) {
                    $config->set($key, $value);
                } else {
                    $config->remove($key);
                }
                $configContent =
                    '<?php // !!! Do not edit this file, it will be overwritten on config change !!!' . PHP_EOL .
                    'return ' . var_export($config->get(null), true) . ';' . PHP_EOL;
                file_put_contents($this->localConfig, $configContent);

                // Clear config file from PHPs OPcache to load it on next request
                if (function_exists('opcache_invalidate')) {
                    opcache_invalidate($this->localConfig, true);
                }
            }

            $value = $options['type'] !== 'password' ? $value : $this->passwordPlaceholder;
            $changes[] = sprintf('%s = %s', $key, json_encode($value));
        }

        if ($changes) {
            $this->log->info(
                'Updated {page} configuration: {changes}',
                [
                    'page' => $page,
                    'changes' => implode(', ', $changes),
                ]
            );

            $this->addNotification('config.edit.success');
        }

        return $this->redirect->back();
    }

    protected function isFileWritable(string $file): bool
    {
        return
            (file_exists($file) && is_writable($file))
            || (!file_exists($file) && is_writable(dirname($file)));
    }

    protected function validation(string $page, Request $request): array
    {
        $rules = [];
        $config = $this->options[$page];
        $settings = $this->filterShownSettings($config['config']);

        // Generate validation rules
        foreach ($settings as $key => $setting) {
            $validation = [];
            $validation[] = empty($setting['required']) ? 'optional' : 'required';
            # Request field names wih . are parsed with _
            $key = Str::replace('.', '_', $key);

            if (
                !empty($setting['validation'])
                // Ignore unchanged passwords
                && !($setting['type'] === 'password' && $request->postData($key) === $this->passwordPlaceholder)
            ) {
                $validation = array_merge($validation, $setting['validation']);
            }

            match ($setting['type']) {
                'string', 'text' => null, // Anything is valid here when optional
                'datetime-local' => $validation[] = 'date_time',
                'date' => $validation[] = 'date',
                'boolean' => $validation[] = 'checked',
                'number' => $validation[] = 'number',
                'url' => $validation[] = 'url',
                'email' => $validation[] = 'email',
                'select' => $validation[] = 'in:' . implode(',', array_keys($setting['data'])),
                'select_multi' => $validation[] = 'array_val|in_many:' . implode(',', array_keys($setting['data'])),
                'password' =>
                $request->postData($key) !== $this->passwordPlaceholder
                && (!empty($setting['required']) || $request->postData($key))
                    ? $validation[] = 'length:' . $this->config->get('password_min_length')
                    : null,
                default => throw new InvalidArgumentException(
                    'Type ' . $setting['type'] . ' of ' . $key . ' is not defined'
                ),
            };

            $rules[$key] = implode('|', $validation);
        }

        if (!empty($config['validation']) && is_callable($config['validation'])) {
            return $config['validation']($request, $rules);
        }

        return $this->validate($request, $rules);
    }

    protected function filterShownSettings(array $settings): array
    {
        // Ignore values from env
        $settings = array_filter($settings, fn($a) => empty($a['in_env']));
        // Skip if permissions don't match
        return array_filter($settings, fn($a) => empty($a['permission']) || $this->auth->can($a['permission']));
    }

    protected function activePage(Request $request): string
    {
        $page = $request->getAttribute('page');

        if (!$page || empty($this->options[$page])) {
            throw new HttpNotFound();
        }

        $permissions = $this->options[$page]['permission'] ?? null;
        if (!empty($permissions) && !$this->auth->can($permissions)) {
            throw new HttpForbidden();
        }

        return $page;
    }

    /**
     * Validation for Event page
     */
    protected function validateEvent(Request $request, array $rules): array
    {
        // Run general validation
        $data = $this->validate($request, $rules);
        $addedRules = [];

        // Ensure event dates are after each other
        $dates = ['buildup_start', 'event_start', 'event_end', 'teardown_end'];
        foreach ($dates as $i => $dateField) {
            if (!$i || !$data[$dateField]) {
                continue;
            }

            foreach (array_slice($dates, 0, $i) as $previousDateField) {
                if (!$data[$previousDateField]) {
                    continue;
                }

                $addedRules[$dateField][] = ['after', $data[$previousDateField], 'true'];
            }
        }

        if (!empty($addedRules)) {
            $this->validate($request, $addedRules);
        }

        return $data;
    }
}
