---
version: "3.6"
services:
  es_server:
    environment:
      MYSQL_HOST: es_database
      MYSQL_USER: helferinnensystem
      MYSQL_PASSWORD:
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: helferinnensystem
      APP_NAME: Helferinnensystem
      CONTACT_EMAIL: "mailto:helfen@froscon.org"
      THEME: 0
      TSHIRT_SIZE_REQUIRED: 'false'
      ANGEL_AUTOARRIVE: 'true'
      SUPPORTERS_CAN_PROMOTE: 'true'
      SIGNUP_POST_FRACTION: 1
      PASSWORD_MINIMUM_LENGTH: 5
      ENABLE_PLANNED_ARRIVAL: 'false'
      ENABLE_FORCE_ACTIVE: 'false'
      GOODIE_TYPE: none
      ENABLE_VOUCHER: 'false'
      NIGHT_SHIFTS: 'false'
      IFSG_ENABLED: 'true'
      IFSG_LIGHT_ENABLED: 'true'
      DEFAULT_LOCALE: de_DE
    secrets:
      - db_password
  es_database:
    environment:
      MYSQL_DATABASE: helferinnensystem
      MYSQL_USER: helferinnensystem
      MYSQL_PASSWORD:
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_RANDOM_ROOT_PASSWORD:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    secrets:
      - db_root_password
      - db_password
  backup:
    image: backup
    build:
      context: ..
      dockerfile: docker/backup.Dockerfile
    depends_on:
      - es_database
    environment:
      MYSQL_HOST: es_database
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    networks:
      - database
    volumes:
      - backup:/backup
    secrets:
      - db_root_password
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: es_database
    networks:
      - database
      - internet
    ports:
      - "5081:80"
    profiles:
      - dev

volumes:
  backup: {}

secrets:
  db_password:
    file: secrets/mysql_pw.txt
  db_root_password:
    file: secrets/mysql_root_pw.txt
