<?php

declare(strict_types=1);

// To change or overwrite some settings, create a config.php

return [
    // Http client service provider timeout. Wait max n seconds for a response.
    'guzzle_timeout' => (float) env('GUZZLE_TIMEOUT', 20.0),

    // Header links
    // Available link placeholders: %lang%
    // To disable a header_item in config.php, you can set its value to null
    'header_items'            => [
        // Name can be a translation string, permission is an engelsystem privilege
        // 'Name' => 'URL',
        // 'some.key' => ['URL', 'permission'],

        //'Foo' => ['https://foo.bar/batz-%lang%.html', 'logout'], // Permission: for logged-in users
    ],

    // Footer links
    // To disable a footer item in config.php, you can set its value to null
    'footer_items'            => [
        // Name can be a translation string, permission is a engelsystem privilege
        // 'Name' => 'URL',
        // 'some.key' => ['URL', 'permission'],

        // URL to faq page
        'faq.faq' => [env('FAQ_URL', '/faq'), 'faq.view'],

        // Contact email address, linked on every page
        'Contact' => env('CONTACT_EMAIL', 'mailto:ticket@c3heaven.de'),
    ],

    // Other ways to ask the heaven
    // Multiple contact options / links are possible, analogue to footer_items
    'contact_options' => [
        // E-mail address
        'general.email' => env('CONTACT_EMAIL', 'mailto:ticket@c3heaven.de'),
    ],

    // Setup external authentication providers
    'oauth'                   => [
        // '[name]' => [config]
        /*
        '[name]' => [
            // Name shown to the user (optional)
            'name' => 'Some Provider',
            // Auth client ID
            'client_id' => 'engelsystem',
            // Auth client secret
            'client_secret' => '[generated by provider]',
            // Authentication URL
            'url_auth' => '[generated by provider]',
            // Token URL
            'url_token' => '[generated by provider]',
            // User info URL which provides userdata
            'url_info' => '[generated by provider]',
            // OAuth Scopes
            // 'scope' => ['openid'],
            // Info unique user id field
            'id' => 'uuid',
            // The following fields are used for registration
            // Info username field (optional)
            'username' => 'nickname',
            // Info email field (optional)
            'email' => 'email',
            // Info first name field (optional)
            'first_name' => 'first-name',
            // Info last name field (optional)
            'last_name' => 'last-name',
            // User URL to provider, linked on provider settings page (optional)
            'url' => '[provider page]',
            // Whether info attributes are nested arrays (optional)
            // For example {"user":{"name":"foo"}} can be accessed using user.name
            'nested_info' => false,
            // Only show after clicking the page title (optional)
            'hidden' => false,
            // Mark user as arrived when using this provider (optional)
            'mark_arrived' => false,
            // If the password field should be enabled on registration (optional)
            'enable_password' => false,
            // Allow registration even if disabled in config (optional)
            'allow_registration' => null,
            // Allow disconnecting user accounts from the oauth provider (optional)
            'allow_user_disconnect' => true,
            // Auto join teams
            // Info groups field (optional)
            'groups' => 'groups',
            // Groups to team (angel type) mapping (optional)
            'teams' => [
                '/Lorem' => 4, // 4 being the ID of the team (angel type)
                '/Foo Mod' => ['id' => 5, 'supporter' => true], // 5 being the ID of the team (angel type)
            ],
        ],
        */
    ],

    // Default theme, 1 = theme1.scss etc.
    'theme'                   => env('THEME', 1),

    // Supported themes
    // To disable a theme in config.php, you can set its value to null
    'themes' => [
        20 => [
            'name' => 'Engelsystem eh22-light (2025)',
            'type' => 'light',
            'navbar_classes' => 'navbar-light',
        ],
        19 => [
            'name' => 'Engelsystem eh22-dark (2025)',
            'type' => 'dark',
            'navbar_classes' => 'navbar-dark',
        ],
        18 => [
            'name' => 'Engelsystem 38c3 (2024) - Lila, Lachs und Kurven',
            'type' => 'dark',
            'navbar_classes' => 'navbar-dark',
        ],
        17 => [
            'name' => 'Engelsystem 37c3 (2023)',
            'type' => 'dark',
            'navbar_classes' => 'navbar-dark',
        ],
        16 => [
            'name' => 'Engelsystem cccamp23 (2023)',
            'type' => 'dark',
            'navbar_classes' => 'navbar-dark',
        ],
        15 => [
            'name' => 'Engelsystem rC3 (2021)',
            'type' => 'dark',
            'navbar_classes' => 'navbar-dark',
        ],
        14 => [
            'name' => 'Engelsystem rC3 teal (2020)',
            'type' => 'dark',
            'navbar_classes' => 'navbar-dark bg-black border-dark',
        ],
        13 => [
            'name' => 'Engelsystem rC3 violet (2020)',
            'type' => 'dark',
            'navbar_classes' => 'navbar-dark bg-black border-dark',
        ],
        12 => [
            'name' => 'Engelsystem 36c3 (2019)',
            'type' => 'dark',
            'navbar_classes' => 'navbar-dark bg-black border-dark',
        ],
        10 => [
            'name' => 'Engelsystem cccamp19 green (2019)',
            'type' => 'dark',
            'navbar_classes' => 'navbar-dark bg-black border-dark',
        ],
        9 => [
            'name' => 'Engelsystem cccamp19 yellow (2019)',
            'type' => 'dark',
            'navbar_classes' => 'navbar-dark bg-black border-dark',
        ],
        8 => [
            'name' => 'Engelsystem cccamp19 blue (2019)',
            'type' => 'dark',
            'navbar_classes' => 'navbar-dark bg-black border-dark',
        ],
        7 => [
            'name' => 'Engelsystem 35c3 dark (2018)',
            'type' => 'dark',
            'navbar_classes' => 'navbar-primary navbar-dark bg-black border-primary',
        ],
        6 => [
            'name' => 'Engelsystem 34c3 dark (2017)',
            'type' => 'dark',
            'navbar_classes' => 'navbar-dark bg-black border-dark',
        ],
        5 => [
            'name' => 'Engelsystem 34c3 light (2017)',
            'type' => 'light',
            'navbar_classes' => 'navbar-light bg-light',
        ],
        4 => [
            'name' => 'Engelsystem 33c3 (2016)',
            'type' => 'dark',
            'navbar_classes' => 'navbar-dark bg-body border-dark',
        ],
        3 => [
            'name' => 'Engelsystem 32c3 (2015)',
            'type' => 'light',
            'navbar_classes' => 'navbar-dark bg-black border-dark',
        ],
        2 => [
            'name' => 'Engelsystem cccamp15',
            'type' => 'light',
            'navbar_classes' => 'navbar-light bg-light',
        ],
        11 => [
            'name' => 'Engelsystem high contrast',
            'type' => 'dark',
            'navbar_classes' => 'navbar-dark bg-black border-dark',
        ],
        0 => [
            'name' => 'Engelsystem light',
            'type' => 'light',
            'navbar_classes' => 'navbar-light bg-light',
        ],
        1 => [
            'name' => 'Engelsystem dark',
            'type' => 'dark',
            'navbar_classes' => 'navbar-dark bg-black border-dark',
        ],
    ],

    // Food Voucher API configuration to request vouchers from the 39C3 middleware
    'food_voucher_api' => [
        'info_url' => (string) env('FOOD_VOUCHER_API_INFO_URL'),
        'post_url' => (string) env('FOOD_VOUCHER_API_POST_URL'),
        'auth_token' => (string) env('FOOD_VOUCHER_API_AUTH_TOKEN'),
        'default_email' => (string) env('FOOD_VOUCHER_API_DEFAULT_EMAIL'),
        'claim_redirect_url' => (string) env('FOOD_VOUCHER_API_CLAIM_REDIRECT_URL'),
        'info_cache' => (int) env('FOOD_VOUCHER_API_INFO_CACHE', 60),
    ],

    // Available T-shirt sizes
    // To disable a t-shirt size in config.php, you can set its value to null
    'tshirt_sizes'            => [
        'S'    => 'Small Straight-Cut',
        'S-F'  => 'Small Fitted-Cut',
        'M'    => 'Medium Straight-Cut',
        'M-F'  => 'Medium Fitted-Cut',
        'L'    => 'Large Straight-Cut',
        'L-F'  => 'Large Fitted-Cut',
        'XL'   => 'XLarge Straight-Cut',
        'XL-F' => 'XLarge Fitted-Cut',
        '2XL'  => '2XLarge Straight-Cut',
        '3XL'  => '3XLarge Straight-Cut',
        '4XL'  => '4XLarge Straight-Cut',
    ],

    // Predefined headers
    // To disable a header in config.php, you can set its value to null
    'headers'                 => [
        'X-Content-Type-Options'  => 'nosniff',
        'X-Frame-Options'         => 'sameorigin',
        'Referrer-Policy'         => 'strict-origin-when-cross-origin',
        'Content-Security-Policy' =>
            'default-src \'self\'; '
            . ' style-src \'self\' \'unsafe-inline\'; '
            . 'img-src \'self\' data:;',
        'X-XSS-Protection'        => '1; mode=block',
        'Feature-Policy'          => 'autoplay \'none\'',
        //'Strict-Transport-Security' => 'max-age=7776000',
        //'Expect-CT' => 'max-age=7776000,enforce,report-uri="[uri]"',
    ],

    // A list of credits
    'credits'                 => [
        'Contribution' => 'Please visit [engelsystem/engelsystem](https://github.com/engelsystem/engelsystem) if '
            . 'you want to contribute, have found any [bugs](https://github.com/engelsystem/engelsystem/issues) '
            . 'or need help.',
    ],
];
