<?php

function engelsystem_email_to_user($user, $title, $message) {
  gettext_locale($user['Sprache']);
  
  $message = sprintf(_("Hi %s,"), $user['Nick']) . "\n\n" . _("here is a message for you from the engelsystem:") . "\n\n" . $message . "\n\n" . _("This email is autogenerated and has not to be signed. You got this email because you are registered in the engelsystem.");
  
  gettext_locale();
  return engelsystem_email($user['email'], $title, $message);
}

function engelsystem_email($address, $title, $message) {
  return mail($address, $title, $message, "Content-Type: text/plain; charset=UTF-8\r\nFrom: Engelsystem <noreply@engelsystem.de>");
}

?>
