INSERT INTO `Sprache` (`TextID`, `Sprache`, `Text`) VALUES ('pub_einstellungen_PictureNoShow', 'DE', 'Das Foto ist nicht freigegeben');
INSERT INTO `Sprache` (`TextID`, `Sprache`, `Text`) VALUES ('pub_einstellungen_PictureNoShow', 'EN', 'The photo isnot free at the moment');
INSERT INTO `Sprache` (`TextID`, `Sprache`, `Text`) VALUES ('pub_einstellungen_PictureShow', 'DE', 'Das Foto ist freigegeben');
INSERT INTO `Sprache` (`TextID`, `Sprache`, `Text`) VALUES ('pub_einstellungen_PictureShow', 'EN', 'The photo is free at the moment');
INSERT INTO `Sprache` (`TextID`, `Sprache`, `Text`) VALUES ('delete', 'DE', 'löschen');
INSERT INTO `Sprache` (`TextID`, `Sprache`, `Text`) VALUES ('delete', 'EN', 'delete');
INSERT INTO `Sprache` (`TextID`, `Sprache`, `Text`) VALUES ('pub_einstellungen_del_OK', 'DE', 'Bild wurde erfolgreich gelöscht.');
INSERT INTO `Sprache` (`TextID`, `Sprache`, `Text`) VALUES ('pub_einstellungen_del_OK', 'EN', 'Picture was deleted successfully.');
INSERT INTO `Sprache` (`TextID`, `Sprache`, `Text`) VALUES ('pub_einstellungen_del_KO', 'DE', 'Bild wurde nicht erfolgreich gelöscht.');
INSERT INTO `Sprache` (`TextID`, `Sprache`, `Text`) VALUES ('pub_einstellungen_del_KO', 'EN', 'Picture was not deleted successfully.');
INSERT INTO `Sprache` (`TextID`, `Sprache`, `Text`) VALUES ('upload', 'DE', 'hochladen');
INSERT INTO `Sprache` (`TextID`, `Sprache`, `Text`) VALUES ('upload', 'EN', 'upload');
INSERT INTO `Sprache` (`TextID`, `Sprache`, `Text`) VALUES ('pub_einstellungen_send_OK', 'DE', 'Die Datei wurde erfolgreich hochgeladen.');
INSERT INTO `Sprache` (`TextID`, `Sprache`, `Text`) VALUES ('pub_einstellungen_send_OK', 'EN', 'The file was uploaded successfully');
INSERT INTO `Sprache` (`TextID`, `Sprache`, `Text`) VALUES ('pub_einstellungen_send_KO', 'DE', 'Beim Hochladen ist ein Fehler aufgetreten.');
INSERT INTO `Sprache` (`TextID`, `Sprache`, `Text`) VALUES ('pub_einstellungen_send_KO', 'EN', 'An error was detected. Please try again!');
INSERT INTO `Sprache` (`TextID`, `Sprache`, `Text`) VALUES ('pub_einstellungen_PictureUpload', 'DE', 'Hier kannst Du ein Foto von Dir hochladen!');
INSERT INTO `Sprache` (`TextID`, `Sprache`, `Text`) VALUES ('pub_einstellungen_PictureUpload', 'EN', 'Feel free to upload a picture of yourself.');
